<option value="1">Afghanistan</option>
<option value="2">Albania</option>
<option value="3">Algeria</option>
<option value="4">Andorra</option>
<option value="5">Angola</option>
<option value="6">Anguilla</option>
<option value="7">Antigua e Barbuda</option>
<option value="8">Antille Olandesi</option>
<option value="9">Arabia Saudita</option>
<option value="10">Argentina</option>
<option value="11">Armenia</option>
<option value="12">Aruba</option>
<option value="13">Australia</option>
<option value="14">Austria</option>
<option value="15">Azerbaigian</option>
<option value="16">Bahamas</option>
<option value="17">Bahrein</option>
<option value="18">Bangladesh</option>
<option value="19">Barbados</option>
<option value="20">Belgio</option>
<option value="21">Belize</option>
<option value="22">Benin</option>
<option value="23">Bermuda</option>
<option value="24">Bhutan</option>
<option value="25">Bielorussia</option>
<option value="26">Bolivia</option>
<option value="27">Bosnia-Erzegovina</option>
<option value="28">Botswana</option>
<option value="29">Bouvet, isola</option>
<option value="30">Brasile</option>
<option value="31">Brunei</option>
<option value="32">Bulgaria</option>
<option value="33">Burkina Faso</option>
<option value="34">Burundi</option>
<option value="35">Cambogia</option>
<option value="36">Camerun</option>
<option value="37">Canada</option>
<option value="38">Capo Verde</option>
<option value="39">Cayman, isole</option>
<option value="40">Ciad</option>
<option value="41">Cile</option>
<option value="42">Cina</option>
<option value="43">Cipro</option>
<option value="44">Cisgiordania</option>
<option value="45">Cocos, isole</option>
<option value="46">Colombia</option>
<option value="47">Comore</option>
<option value="48">Congo</option>
<option value="49">Congo, Repubblica Democratica del</option>
<option value="50">Cook, isole</option>
<option value="51">Corea del Nord</option>
<option value="52">Corea del Sud</option>
<option value="53">Costa d&#39;avorio</option>
<option value="54">Costa Rica</option>
<option value="55">Croazia</option>
<option value="56">Cuba</option>
<option value="57">Danimarca</option>
<option value="58">Dominica</option>
<option value="59">Ecuador</option>
<option value="60">Egitto</option>
<option value="61">El Salvador</option>
<option value="62">Emirati Arabi Uniti</option>
<option value="63">Eritrea</option>
<option value="64">Estonia</option>
<option value="65">Etiopia</option>
<option value="66">Faroe, isole</option>
<option value="67">Figi</option>
<option value="68">Filippine</option>
<option value="69">Finlandia</option>
<option value="70">Francia</option>
<option value="71">Gabon</option>
<option value="72">Gambia</option>
<option value="73">Georgia</option>
<option value="74">Georgia Meridionale e isole Sandwich del Sud</option>
<option value="75">Germania</option>
<option value="76">Ghana</option>
<option value="77">Giamaica</option>
<option value="78">Giappone</option>
<option value="79">Gibilterra</option>
<option value="80">Gibuti</option>
<option value="81">Giordania</option>
<option value="82">Grecia</option>
<option value="83">Grenada</option>
<option value="84">Groenlandia</option>
<option value="85">Guadalupa</option>
<option value="86">Guam</option>
<option value="87">Guatemala</option>
<option value="88">Guiana</option>
<option value="89">Guiana francese</option>
<option value="90">Guinea</option>
<option value="92">Guinea Equatoriale</option>
<option value="91">Guinea-Bissau</option>
<option value="93">Haiti</option>
<option value="94">Honduras</option>
<option value="95">Hong Kong</option>
<option value="96">India</option>
<option value="97">Indonesia</option>
<option value="98">Iran</option>
<option value="99">Iraq</option>
<option value="100">Irlanda</option>
<option value="101">Islanda</option>
<option value="102">Isole del Natale</option>
<option value="103">Isole Falkland (Isole Malvine)</option>
<option value="104">Isole Heard e McDonald</option>
<option value="105">Isole Pitcairn</option>
<option value="106">Isole Vergini britanniche</option>
<option value="107">Isole Vergini statunitensi</option>
<option value="108">Israele</option>
<option selected="selected" value="109">Italia</option>
<option value="110">Kazakistan</option>
<option value="111">Kenya</option>
<option value="112">Kirghizistan</option>
<option value="113">Kiribati</option>
<option value="114">Kuwait</option>
<option value="115">Laos</option>
<option value="116">Lesotho</option>
<option value="117">Lettonia</option>
<option value="118">Libano</option>
<option value="119">Liberia</option>
<option value="120">Libia</option>
<option value="121">Liechtenstein</option>
<option value="122">Lituania</option>
<option value="123">Lussemburgo</option>
<option value="124">Macao</option>
<option value="125">Macedonia, Ex Repubblica iugoslava di</option>
<option value="126">Madagascar</option>
<option value="127">Malawi</option>
<option value="128">Maldive</option>
<option value="129">Malesia</option>
<option value="130">Mali</option>
<option value="131">Malta</option>
<option value="132">Marianne Settentrionali, isole</option>
<option value="133">Marocco</option>
<option value="134">Marshall, isole</option>
<option value="135">Martinica</option>
<option value="136">Mauritania</option>
<option value="137">Mauritius</option>
<option value="138">Mayotte</option>
<option value="139">Messico</option>
<option value="140">Micronesia, Stati Federati della</option>
<option value="141">Moldavia</option>
<option value="142">Monaco</option>
<option value="143">Mongolia</option>
<option value="144">Montserrat</option>
<option value="145">Mozambico</option>
<option value="146">Myanmar</option>
<option value="147">Namibia</option>
<option value="148">Nauru</option>
<option value="149">Nepal</option>
<option value="150">Nicaragua</option>
<option value="151">Niger</option>
<option value="152">Nigeria</option>
<option value="153">Niue</option>
<option value="154">Norfolk, isola</option>
<option value="155">Norvegia</option>
<option value="156">Nuova Caledonia</option>
<option value="157">Nuova Zelanda</option>
<option value="158">Oman</option>
<option value="159">Paesi Bassi</option>
<option value="160">Pakistan</option>
<option value="161">Palau</option>
<option value="162">Panama</option>
<option value="163">Papua Nuova Guinea</option>
<option value="164">Paraguay</option>
<option value="165">Per&#249;</option>
<option value="166">Polinesia Francese</option>
<option value="167">Polonia</option>
<option value="168">Portogallo</option>
<option value="169">Portorico</option>
<option value="170">Qatar</option>
<option value="171">Regno Unito</option>
<option value="172">Repubblica Ceca</option>
<option value="173">Repubblica Centrafricana</option>
<option value="174">Repubblica Dominicana</option>
<option value="175">Riunione, isola di</option>
<option value="176">Romania</option>
<option value="177">Ruanda</option>
<option value="178">Russia</option>
<option value="179">Sahara occidentale</option>
<option value="180">Saint Kitts e Nevis</option>
<option value="182">Saint Vincent e Grenadine</option>
<option value="181">Saint-Pierre e Miquelon</option>
<option value="183">Salomone, isole</option>
<option value="184">Samoa</option>
<option value="185">Samoa Americane</option>
<option value="186">San Marino</option>
<option value="189">Sant&#39;Elena</option>
<option value="187">Santa Lucia</option>
<option value="188">Santa Sede (Citt&#224; del Vaticano)</option>
<option value="190">Sao Tom&#232; e Principe</option>
<option value="191">Senegal</option>
<option value="192">Serbia e Montenegro</option>
<option value="193">Seychelles</option>
<option value="194">Sierra Leone</option>
<option value="195">Singapore</option>
<option value="196">Siria</option>
<option value="197">Slovacchia</option>
<option value="198">Slovenia</option>
<option value="199">Somalia</option>
<option value="200">Spagna</option>
<option value="201">Sri Lanka</option>
<option value="202">Stati Uniti</option>
<option value="203">Striscia di Gaza</option>
<option value="204">Sudafrica</option>
<option value="205">Sudan</option>
<option value="206">Suriname</option>
<option value="207">Svalbard</option>
<option value="208">Svezia</option>
<option value="209">Svizzera</option>
<option value="210">Swaziland</option>
<option value="211">Tagikistan</option>
<option value="212">Tailandia</option>
<option value="213">Taiwan</option>
<option value="214">Tanzania</option>
<option value="215">Terre Australi e Antartiche Francesi</option>
<option value="216">Territori Britannici dell&#39;Oceano Indiano</option>
<option value="217">Timor Est</option>
<option value="218">Togo</option>
<option value="219">Tokelau</option>
<option value="220">Tonga</option>
<option value="221">Trinidad e Tobago</option>
<option value="222">Tunisia</option>
<option value="223">Turchia</option>
<option value="224">Turkmenistan</option>
<option value="225">Turks e Caicos</option>
<option value="226">Tuvalu</option>
<option value="227">Ucraina</option>
<option value="228">Uganda</option>
<option value="229">Ungheria</option>
<option value="230">Uruguay</option>
<option value="231">Uzbekistan</option>
<option value="232">Vanuatu</option>
<option value="233">Venezuela</option>
<option value="234">Vietnam</option>
<option value="235">Wallis e Futuna</option>
<option value="236">Yemen</option>
<option value="237">Zambia</option>
<option value="238">Zimbabwe</option><?php /**PATH C:\Users\Aguer\OneDrive - Università degli Studi di Catania\Desktop\Ingegneria Informatica\Database and Web Programming\Web programming\Rtl.it\hw2\resources\views/layouts/nazioni.blade.php ENDPATH**/ ?>